# Backwards-compatibility shim. The version is now provided by importlib.metadata
# rather than being generated by setuptools-scm. This module exists so that
# `from numcodecs.version import version` continues to work.
from importlib.metadata import version as _version

__version__: str = _version("numcodecs")
version: str = __version__
