version: 2

submodules:
  include: all

build:
  os: ubuntu-20.04
  tools:
    python: "3.12"
  jobs:
    post_install:
      - python -m pip install --pre 'zarr>=3.0.0b2'

sphinx:
  configuration: docs/conf.py

python:
  install:
    - method: pip
      path: .
      extra_requirements:
        - docs
        - msgpack
        - zfpy
        - crc32c
