version: 2

submodules:
  include: all

build:
  os: ubuntu-20.04
  tools:
    python: "3.9"

sphinx:
  configuration: docs/conf.py

python:
  install:
    - requirements: requirements_rtfd.txt
    - method: pip
      path: .
