
branches:
  only:
    - master

sudo: false

addons:
  apt:
    packages:
      - liblzma-dev

matrix:
  include:
    - os: linux
      language: python
      python: 2.7
    - os: linux
      language: python
      python: 3.5
    - os: linux
      language: python
      python: 3.6
    - os: linux
      language: python
      python: 3.7
      dist: xenial
    - os: linux
      language: python
      python: 3.8
      dist: xenial
      sudo: true
    - os: osx
      language: generic

install:
  - pip install -U tox-travis coveralls pip setuptools wheel pytest
  - pip install -v -e .

script:
  - if [ "$TRAVIS_OS_NAME" = "linux" ]; then tox; fi
  - if [ "$TRAVIS_OS_NAME" = "osx" ]; then pytest -v --pyargs numcodecs; fi

after_success:
  - if [ "$TRAVIS_OS_NAME" = "linux" ]; then coveralls; fi

