
branches:
  only:
    - master

sudo: false

addons:
  apt:
    packages:
      - liblzma-dev

matrix:
  include:
    - os: linux
      language: python
      python: 3.5
    - os: linux
      language: python
      python: 3.6
    - os: linux
      language: python
      python: 3.7
      dist: xenial
    - os: linux
      language: python
      python: 3.8
      dist: xenial
      sudo: true

install:
  - pip install -U tox-travis coveralls pip setuptools wheel pytest
  - pip install -v -e .

script:
  - tox

after_success:
  - coveralls --service=travis-pro

