name: Tests on Pyodide

on: [push, pull_request]

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

permissions: {}

jobs:
  build:
    name: Build numcodecs WASM distribution
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          submodules: recursive
          fetch-tags: true
        # TODO: build for Pyodide 314.0.0 stable when released and added to cibuildwheel
        # hopefully this will happen for us in sync with cibuildwheel v4.0.0 stable as well
      - name: Build and test numcodecs for Pyodide
        uses: pypa/cibuildwheel@54327ab9d35de03b359ac25c97de9417d94639c0 # v4.0.0rc1
        env:
          CIBW_ENABLE: pyodide-prerelease
        with:
          only: cp314-pyodide_wasm32
